# put workflow script there
# download data
rule download:
    shell:
        "python download.py"

rule clean_raw:
    shell:
        "stata-mp -s do clean.do"

rule audit:
    shell:
        "stata-mp -s do audit.do"


