# put workflow script there
# download data
rule download:
    shell:
        "python code/download.py"

rule clean_raw:
    shell:
        "stata-mp code/clean.do"

rule audit:
    shell:
        "stata-mp code/audit"


